---
Style/ClassAndModuleChildren:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'
Style/RedundantReturn:
  Enabled: false
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
